const numberData = [
  { num: 1, text: "one" },
  { num: 2, text: "two" },
  { num: 3, text: "three" },
  { num: 4, text: "four" },
  { num: 5, text: "five" },
  { num: 6, text: "six" },
  { num: 7, text: "seven" },
  { num: 8, text: "eight" },
  { num: 9, text: "nine" },
  { num: 10, text: "ten" },
  { num: 11, text: "eleven" },
  { num: 12, text: "twelve" },
  { num: 13, text: "thirteen" },
  { num: 14, text: "fourteen" },
  { num: 15, text: "fifteen" },
  { num: 16, text: "sixteen" },
  { num: 17, text: "seventeen" },
  { num: 18, text: "eighteen" },
  { num: 19, text: "nineteen" },
  { num: 20, text: "twenty" },
  { num: 30, text: "thirty" },
  { num: 40, text: "forty" },
  { num: 50, text: "fifty" },
  { num: 60, text: "sixty" },
  { num: 70, text: "seventy" },
  { num: 80, text: "eighty" },
  { num: 90, text: "ninety" },
  { num: 100, text: "one hundred" },
  { num: 200, text: "two hundred" },
  { num: 300, text: "three hundred" },
  { num: 400, text: "four hundred" },
  { num: 500, text: "five hundred" },
  { num: 600, text: "six hundred" },
  { num: 700, text: "seven hundred" },
  { num: 800, text: "eight hundred" },
  { num: 900, text: "nine hundred" },
  { num: 1000, text: "one thousand" },
];
